services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: main
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_ai_ci
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/initdb:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped

volumes:
  dbdata: {}
