services:
  app:
    image: ${DOCKERHUB_USERNAME}/seokvey-api:latest
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_ADDITIONAL_LOCATION: /config/   # ← 이 경로를 보도록
    volumes:
      - /srv/seokvey/config:/config                 # ← 서버의 설정을 컨테이너로
    ports:
      - "8080:8080"
    env_file:
      - ./seokvey.env
    depends_on: [db]
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: main
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_ai_ci
    volumes:
      - dbdata:/var/lib/mysql
    restart: unless-stopped

volumes:
  dbdata: {}
