services:
  app:
    image: ${DOCKERHUB_USERNAME}/seokvey-api:latest
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8080:8080"
    env_file:
      - ./seokvey.env
    depends_on: [db]
    restart: unless-stopped
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "5"

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: main
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_ai_ci
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/initdb:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped
    logging:
      driver: local          # 또는 json-file
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  dbdata: {}
